FROM sinkcup/laravel-demo:6
MAINTAINER sinkcup <sinkcup@gmail.com>

RUN apt-get update \
    && apt-get install -y \
    git \
    librsvg2-bin \
    vim
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug
RUN apt-get clean \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN composer install

#RUN npm run development
